spring.application.name=voting_semulation

server.port=8080
spring.datasource.url=jdbc:mysql://localhost:3306/voting_BD
spring.datasource.username=root
spring.datasource.password=Amanrana@123
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
app.jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
app.jwt.expiration-ms=86400000
app.cors.allowed-origins=*